---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" $ }}
data:
  watcher.sh: |
    #!/bin/sh
    echo "Listening for close_write events at /core"

    inotifywait -m {{ .Values.core_pattern.path }} -e close_write | while read path action file; do
      aws s3 mv "$path$file" "s3://${AWS_BUCKET}/$file"
      curl -s -X "POST" "https://api.telegram.org/bot${TOKEN}/sendMessage" \
       -H "Content-Type: application/x-www-form-urlencoded; charset=utf-8" \
       --data-urlencode "text=Segfault happens at \`${NODE_NAME}\`\. Download coredump with: \`aws s3 cp s3://${AWS_BUCKET}/$file \.\`" \
       --data-urlencode "chat_id=${CHAT_ID}" \
       --data-urlencode "disable_web_page_preview=true" \
       --data-urlencode "parse_mode=MarkdownV2"
    done

    echo "Stop watcher"
