---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" $ }}
type: Opaque
data:
  aws_bucket:     {{ .Values.secrets.aws_bucket | b64enc | quote }}
  aws_key_id:     {{ .Values.secrets.aws_key_id | b64enc | quote }}
  aws_key_secret: {{ .Values.secrets.aws_key_secret | b64enc | quote }}
  aws_region:     {{ .Values.secrets.aws_region | b64enc | quote }}
  chat_id:        {{ .Values.secrets.chat_id | b64enc | quote }}
  telegram_token: {{ .Values.secrets.telegram_token | b64enc | quote }}
